In [2]:
######### Batches 
import numpy as np 

inputs = [[1.0,2.0,3.0,2.5],[2.0,5.0,3.1,-1.3],[4.2,2.3,0.3,-2.1]]
weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.19,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]

In [4]:
layer_outputs = []

output = np.dot(inputs,np.array(weights).T) + biases


print(output)

[[ 4.8    2.65   2.385]
 [ 3.55   4.506 -1.974]
 [ 2.43   5.791 -2.989]]


In [12]:
######### Layers
class Layer_Dense:
    def __init__(self,n_inputs,n_outputs) -> None:
        self.weights = 0.10 * np.random.randn(n_inputs,n_outputs)
        self.bias = np.zeros((1,n_outputs))
    
    def forward(self,input):
        output = np.dot(input,self.weights) + self.bias
        return output


In [14]:
X = [[1.0,2.0,3.0,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-0.8]]
layer1 = Layer_Dense(4,4)
layer2 = Layer_Dense(4,3)
layer3 = Layer_Dense(3,1)
layer3.forward(layer2.forward(layer1.forward(X)))

array([[ 5.09709317e-05],
       [-7.19054934e-03],
       [-5.22690146e-03]])